### ISSUE TITLE
Crash With Fabric API 0.12.0 build 313

### ISSUE THREAD

**Issue by Ninja-Hinja42** [BackportProjectMC/PerspectiveModRedux#1]
Crash Report is here:
https://pastebin.com/AMSZNEA3
The game only crashed with this version of Fabric API (the latest version currently).
No other mods, just PerspectiveMod and Fabric API.
Fabric Loader Version is 0.8.7+build.201 (the latest version currently)
I am on 1.15.2, I did not check snapshot versions.

**Comment by Cynosphere** [comment]
[Should be up in a bit](https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/files/2981602)
