### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by andreasdc** [BackportProjectMC/PerspectiveModRedux#17]
[15:49:57] [main/WARN]: Mod `perspectivemod` (0.0.5_01) does not respect SemVer - comparison support is limited.

After switching fabric loader to 0.12.5

**Comment by K0-RR** [comment]
This does not prevent the mod from loading. It's just information about using uncommon versioning

>After switching fabric loader to 0.12.5

I'm sure the loader version doesn't matter here - you would get the same warning on 0.11.7.

**Comment by andreasdc** [comment]
> This does not prevent the mod from loading. It's just information about using uncommon versioning
> 
> > After switching fabric loader to 0.12.5
> 
> I'm sure the loader version doesn't matter here - you would get the same warning on 0.11.7.

I don't know, after changing loader version it doesn't work.

It works now, I have no clue what happened.

**Comment by Cynosphere** [comment]
There's nothing I can do if there's no error log or what not.
