### ISSUE TITLE
Required dependency is not marked as required.

### ISSUE THREAD

**Issue by K0-RR** [BackportProjectMC/PerspectiveModRedux#7]
Judging by the jars section in the fabric.mod.json file mods `Cloth Config API` and `Auto Config Updated API` are required but they aren't mentioned in the depends section.

```
  "depends": {
    "fabricloader": "\u003e\u003d0.4.0",
    "fabric": "*"
  },
  "jars": [
    {
      "file": "META-INF/jars/config-2-4.8.3.jar"
    },
    {
      "file": "META-INF/jars/autoconfig1u-3.3.1.jar"
    }
  ]
```

**Comment by Cynosphere** [comment]
Loader doesn't complain, it works fine and they're marked as Embedded Library on CurseForge. Unless loader starts to complain about it, it's a non issue.
