### ISSUE TITLE
Crash with Ok Zoomer

### ISSUE THREAD

**Issue by sschlester** [BackportProjectMC/PerspectiveModRedux#9]
By using a `@Redirect` mixin, Perspective Mod Redux is incompatible with Ok Zoomer. (EnnuiL/OkZoomer#28)

################

Mods loaded:
[✔️] fabric-api-0.36.0+1.17
[✔️] okzoomer-5.0.0-beta.2+1.17
[✔️] PerspectiveModRedux-1.17-0.0.5

Crash log: https://pastebin.com/ykQZksv9

**Comment by Cynosphere** [comment]
Yeah and it crashes Meteor Client too. Oh well. There's simply no other cleaner way to do it without extracting it out to an API.

**Comment by Cynosphere** [comment]
Nevermind there is a cleaner way to do this.

**Comment by Cynosphere** [comment]
https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/files/3367098

**Comment by IceColdTray** [comment]
Issue still exists with
fabric-api-0.37.1+1.17
okzoomer-5.0.0-beta.2+1.17
PerspectiveModRedux-1.17-0.0.5

**Comment by Cynosphere** [comment]
doesnt look like you updated to 0.0.5_01

**Comment by jakobkmar** [comment]
The fix in bf423a3 should be undone as as soon as the above PR has been merged, as it fixes the incompatibility. The fix in bf423a3 just assumes that there is nothing after the `changeLookDirection` call in the `updateMouse` function, which is true at the moment, but can change at any time.
